apiVersion: v2
name: logsnare-engine
description: A Kubernetes log monitoring agent that captures error logs and stores them in various backends
type: application
version: 1.1.0
appVersion: "0.2.1"
keywords:
  - monitoring
  - logging
  - kubernetes
  - error-tracking
maintainers:
  - name: DevOpsArts
    url: https://github.com/devopsarts
home: https://github.com/devopsarts/logsnare
sources:
  - https://github.com/devopsarts/logsnare
