{{- if .Values.namespace.create }}
# Logsnare - Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "logsnare.namespace" . }}
  labels:
    {{- include "logsnare.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
{{- end }}
